apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  namespace: default
  name: tech-docs
  title: tech-docs
  description: testing tech-docs
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: library
  lifecycle: production
  owner: group:test
  system: devops
